# do a release after ci user has pushed the tag to main

on:
  push:
    branches: [main]
    tags:
      - 'v*.*.*'
jobs:
  gh-release:
    # only run on ci commits
    if: "contains(github.event.head_commit.author.name, 'SAP Mentors & Friends')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # read all commit messages since the last tag
      - name: get commit messages
      - run: |
          LOG=`git log --oneline $(git describe --tags --abbrev=0 @^)..@`
          echo "$LOG" > _BODY
          echo ::set-env name=BODY::${_BODY}
      - name: set tag to env var
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: Release ${{ env.RELEASE_VERSION }}
          body: ${{ env.BODY }}
          draft: false
          prerelease: false
